### ISSUE TITLE
Track number of bytes and runes of input for each output?

### ISSUE THREAD

**Issue by whereswaldon** [go-text/shaping#10]
While trying to leverage this text shaper in Gio's editor, I find that I need to be able to quickly map between a glyph of shaped text and the position within the text's raw bytes/runes. In order to facilitate that (somewhat) efficiently, I'm tracking the number of runes and bytes of input data correspond to each output, as well as the position of each output within a larger body of text. In my case, each output is a line of wrapped text, and knowing the length and position of each one means that I can quickly jump to the beginning or end of any line's raw data rather than traversing the entire data slice decoding runes and matching them to glyph clusters.

I'm uncertain how general this need is. I'm relatively sure that other applications will want to be able to quickly traverse raw text data to the position corresponding to a glyph, and therefore might want this data to accelerate that operation. What do you all think? Is this something desirable to add to the shaper?

**Comment by benoitkugler** [comment]
I think your need is tightly related to the notion of clusters, as discussed in https://github.com/go-text/shaping/pull/1#discussion_r652152621 for instance.

Using Harfbuzz clusters and following https://github.com/go-text/shaping/pull/1#discussion_r652152621, we may indeed expose a somewhat more convenient information to the user. 
We could start with a pair of `(startIndex, length)` identifying the origin in the rune slice of each glyph, that could be added to the `Glyph` struct, maybe even replacing the current `Cluster` field.
That should make the conversion from glyph to rune easy.

It would not totally cover the rune to glyph conversion, in case of multiple glyphs for one rune : to do so, we could add a third integer field : the number of _glyphs_ of the current cluster.

Example :

If the input rune slice [r0,r1,r2,r3,r4] is shaped as [g0, g1, g2, g3] with : 

- r0 -> g0 (one to one, the easier case)
- r1, r2 -> g1 (ligature)
- r3 ->  g2, g3 (decomposition)

then the three integers for each glyphs would be (in order)

(0,1,1)
(1,2,1)
(3,1,2)
(3,1,2)

**Comment by andydotxyz** [comment]
In the Fyne editor there is a more naive approach - ask the shaper what position a rune is at in the output.
That way the shaper does not have to expose all of the internal details in a format that can be consumed easily.

Is it really a big overhead to take this approach? In my experience we only need this in response to user input to position a cursor or selection overlay...

**Comment by whereswaldon** [comment]
@andydotxyz Interesting. How does that interact with line wrapping? Also, how do you invert it (ask what rune corresponds to a given visible glyph)?

**Comment by andydotxyz** [comment]
The wrapping algorithm iterates runes to see where the boundaries are and splits the runs at that position.
This happens on string change or size change so the output is cached for render so we don't have multiple passes.

I'm not sure that we do a lookup from glyph to rune - can you indicate why we might do that so I can explore (as I indicated before this is the result of various contributions).
Mostly we consider rendering (therefore the glyphs) to be the output and try not to do reverse lookups.
For example when capturing selected text we find which two runes the cursor is effectively between so we can just work in codepoint space at the API level.

**Comment by whereswaldon** [comment]
Hmm. I don't think that iterating by rune for line wrapping is viable in the world of ligatures and complex scripts. That iteration needs to be glyph-cluster-oriented instead. The results are still cache-able, and definitely should be though.

Looking up the rune for a given glyph is generally a hit testing operation, but I think there are other ways to implement it.

I've put together an implementation of @benoitkugler's suggestion above in #11, and I think it looks reasonable and solves the problem without requiring us to anticipate every kind of positional query that an API consumer _might_ want to make. I'd prefer to address the problem in this way.

**Comment by whereswaldon** [comment]
This was resolved by #11
