### ISSUE TITLE
Code structure

### ISSUE THREAD

**Issue by benoitkugler** [go-text/shaping#2]
Hi, 
I was wondering if a multi-module setup was the best code organization. Correct me if I'm wrong, but I think the modules font, shaping, bidi, etc... will be developed in sync, and a major change in one of the modules will likely require adaption of the others. 
So, isn't one big module, with several sub-packages, a better choice ? 

It's really a naive question/suggestion as I have no experience with multi-modules project !

**Comment by stuartmscott** [comment]
Great point Beniot!

IMO multi-modules enforces a separation of concerns better than sub-packages, but you're right that it can introduce a slowdown when a major change touches several. When I have used multi-modules in the past I ended up with a lot of commits that just bump the version of a dependency in go.mod.

We can certainly restructure the repos if this becomes an issue, tho it maybe a little soon as we're still exploring/experimenting.

What do others think?

**Comment by whereswaldon** [comment]
I think we should run with the current setup until we experience its downsides and then adapt as needed. I don't have strong opinions on the structure, but I'd like to see what constraints that we actually run in to during implementation before trying to make many decisions about it. 

Other opinions?

**Comment by andydotxyz** [comment]
That sounds good. The API definition is pretty clean so the chances of major conflict are low.

**Comment by whereswaldon** [comment]
I'm increasingly sympathetic to @benoitkugler 's original point here. I don't think we're really seeing value from separating the modules. It has mostly served to fragment our discussion across several repos. Perhaps when we migrate content from Benoit's textlayout project it would make more sense, but even then I kinda think packages would be a fine way to keep things separated.

I've felt some friction from having multiple modules as I work with #5, which is where this comment is coming from.

**Comment by benoitkugler** [comment]
As a new example of possible friction, the implementation of #8 would be made cleaner by adding a method to our currently empty `font.Font` interface (I've opened https://github.com/go-text/font/pull/3 to do so).

As in this case, the addition of functionality in the shaper will likely be linked by change in the font representation. 
So I would advocate again for a single module (for now composed of the shaping and font packages).

**Comment by andydotxyz** [comment]
If we are to move to a monorepo we *must* have a clear definition of the roles of each package.
Otherwise the changing areas of responsibility will make it harder to manage and keep clean separations.

**Comment by benoitkugler** [comment]
> If we are to move to a monorepo we _must_ have a clear definition of the roles of each package.
> Otherwise the changing areas of responsibility will make it harder to manage and keep clean separations.

Agreed. I think that we have started from the lower level (harbuzz) and that we start to understand the higher levels needed (bidi, line breaking, etc..) but it still need to be clarified. 

I would propose a separation in three packages (that simply follows the current module structure): 

- `font` implements reading and parsing a font file, and producing an in memory representation that can be used by the shaper
- `harbuzz` is the port of the C library and provides low level shaping of a run of runes with constant properties (font, size, direction, etc...). For now we use `textlayout/harbuzz`, with the aim to eventually merge it to go-text.
- `shaping` leverages `harbuzz` to handle full text paragraphs. It could contain sub-packages, like bidi or hyphenation.

**Comment by andydotxyz** [comment]
> Agreed. I think that we have started from the lower level (harbuzz) and that we start to understand the higher levels needed (bidi, line breaking, etc..) but it still need to be clarified.

Actually we started from a high level definition (see first Commits) and then the harfbuzz details were added and it changed from being a high level abstraction to being specific to harfbuzz. This is why I found it difficult to adapt the code to work in Fyne - we now have two code paths to load fonts - one that loads generic golang.org.x fonts that we used before and need for rendering and the additional harfbuzz font load needed to work with go-text APIs.

i am working on a PR that allows us to hide these internal details so you could just use go-text without needing to pre-process using one of our dependencies as inputs.

**Comment by whereswaldon** [comment]
@benoitkugler I'm happy with that package structure for now.

**Comment by whereswaldon** [comment]
We merged them all in go-text/typesetting#1
