### ISSUE TITLE
What license should go-text use?

### ISSUE THREAD

**Issue by whereswaldon** [go-text/shaping#6]
We need to choose a license for go-text's repositories, or nobody can actually consume the code without violating someone's copyright.

Please share proposals for a licensing choice here. Some things to consider:

- does the license impact who will contribute, and in what way?
- does the license impact whether or not we can merge existing code (such as @benoitkugler 's harfbuzz port) into the same repository?
- how compatible is the license with projects interested in consuming go-text?

**Comment by andydotxyz** [comment]
I would propose we match the rest of the main Go repositories and use BSD. In my mind it is the right balance between openness and usefulness.

**Comment by eliasnaur** [comment]
I believe we should aim for maximum compatibility. A union of the Fyne, Go, Gio licenses seems to achieve that: dual licensed BSD+Unlicense.

I know that there are concerns about the Unlicense, but note that it's possible to remove it later if we deem it necessary, without asking contributors. However, we can't add the Unlicense later without asking every copyright holder (and keeping a record of their consent).

**Comment by whereswaldon** [comment]
I would also propose a dual BSD+Unlicense (or BSD+CC0 if preferred). This project is effectively meant to be the bedrock upon which the Go ecosystem can finally build visual multilingual text applications. I think that enabling Go projects to consume this code with as little friction as possible is important, and public domain has the least possible friction on consumption.

To address the questions that I asked above:

- does the license impact who will contribute, and in what way?
  - @andydotxyz has expressed concerns that corporations may not be comfortable contributing code into the public domain, and has made good-faith efforts to validate that. It definitely seems like the public domain might stop some companies from contributing. However, I'd like to propose that we wait until someone actually raises the issue to say "I can't contribute because of the Unlicense" before we commit to not placing this in the public domain. As @eliasnaur points out, you can always _stop_ contributing to the public domain, but starting later is very hard.
- does the license impact whether or not we can merge existing code (such as @benoitkugler 's harfbuzz port) into the same repository?
  - this is a thorny question. I _thought_ that @benoitkugler's work must match the license of harfbuzz given that it's a "derived work", but then I read the [old MIT license that harfbuzz uses.](https://github.com/harfbuzz/harfbuzz/blob/main/COPYING). It doesn't place restrictions on derived works. By porting all of the code, does @benoitkugler now have a copyright to the new code and thereby the right to relicense it? I'm shaky on this point. If the harfbuzz code must remain Old MIT, then we're going to have multiple licenses under all of the proposed schemes. If it can be relicensed, I suppose much depends on how @benoitkugler prefers to license it (given that it was a colossal amount of work).
- how compatible is the license with projects interested in consuming go-text?
  - the dual BSD+Unlicense is maximally compatible, which is its primary strength. Projects need to no additional work whatsoever to consume it.

**Comment by benoitkugler** [comment]
> If it can be relicensed, I suppose much depends on how @benoitkugler prefers to license it.

For what matters, I've really no strong opinion about the license, so I would choose what is needed here.

**Comment by andydotxyz** [comment]
> * However, I'd like to propose that we wait until someone actually raises the issue to say "I can't contribute because of the Unlicense" before we commit to not placing this in the public domain. As @eliasnaur points out, you can always _stop_ contributing to the public domain, but starting later is very hard.

I did a poll on Twitter... it showed that 24 of 26 respondents work for companies that do not support contributing under an Unlicense/public domain model.
I think my concern stands. https://twitter.com/andydotxyz/status/1456659306674376709

![screenshot-20211109T232847](https://user-images.githubusercontent.com/294436/141022370-a9d63b17-cfaf-4615-bc30-86bd6f058285.png)

**Comment by andydotxyz** [comment]
> * does the license impact who will contribute, and in what way?

Using a business-approved permissive license seems to attract the broadest possible set of contributors.
So far the objections to this license are by those who prefer Unlicense - but to my knowledge there was no expression that they could not contribute under a permissive license instead.

> * does the license impact whether or not we can merge existing code (such as @benoitkugler 's harfbuzz port) into the same repository?

I am not a lawyer, but given that Benoit is the sole contributor of the code in that port I don't think that the choice of license to use should be of worry.
If the source license of harfbuzz is an issue then it probably overrules the rest of this discussion.

> * how compatible is the license with projects interested in consuming go-text?

I am not aware of any projects that will use this that require public domain code for their dependencies. If they did then most of Go and golang.org libraries would be unusable. So permissive MIT/BSD should be usable for all projects.

**Comment by eliasnaur** [comment]
>     * does the license impact whether or not we can merge existing code (such as @benoitkugler 's harfbuzz port) into the same repository?
>       
>       * this is a thorny question. I _thought_ that @benoitkugler's work must match the license of harfbuzz given that it's a "derived work", but then I read the [old MIT license that harfbuzz uses.](https://github.com/harfbuzz/harfbuzz/blob/main/COPYING). It doesn't place restrictions on derived works. By porting all of the code, does @benoitkugler now have a copyright to the new code and thereby the right to relicense it? I'm shaky on this point. If the harfbuzz code must remain Old MIT, then we're going to have multiple licenses under all of the proposed schemes. If it can be relicensed, I suppose much depends on how @benoitkugler prefers to license it (given that it was a colossal amount of work).
> 

Rights not mentioned in a license are retained by the copyright holder. If the Old MIT license doesn't mention relicensing, we can't. It wouldn't make sense anyway: if we could relicense, what's different from the public domain?

> does the license impact whether or not we can merge existing code (such as @benoitkugler 's harfbuzz port) into the same repository?

Sorry for missing this question. If @benoitkugler supports merging his code and continuing maintenance in go-text, and it makes sense to do so (for example, we may want to iteratively make the HB port more Go-like, while keeping the HB tests passing), I'm ok with using (only) the same license as HB (Old MIT).

> I did a poll on Twitter... it showed that 24 of 26 respondents work for companies that do not support contributing under an Unlicense/public domain model.

doesn't necessarily follow from

> "what is the most permissive license your company has approved"

It may simply be the case that the companies in question have never needed to contribute to a public domain project.

> Using a business-approved permissive license seems to attract the broadest possible set of contributors.
> So far the objections to this license are by those who prefer Unlicense - but to my knowledge there was no expression that they could not contribute under a permissive license instead.

This unfairly weighs (still hypothetical) business concerns over the concerns of actual contributors. I prefer contributing to a public domain project by far, but may choose to contribute to a non-public domain project for practical reasons. I can't see why businesses should not also be asked to weigh practicality against convictions.

**Comment by whereswaldon** [comment]
> Rights not mentioned in a license are retained by the copyright holder. If the Old MIT license doesn't mention relicensing, we can't. It wouldn't make sense anyway: if we could relicense, what's different from the public domain?

Well, the question is really about whether or not a source port that no longer contains code from the original project is by default under the same license. @benoitkugler wrote the code, though using harfbuzz as a reference. Unlike the GPL, which virally requires that derived works in this fashion retain the same license, I don't see anything indicating that the Old MIT would work that way. Does anyone know a FOSS lawyer or licensing expert who could offer more informed thoughts?

> I did a poll on Twitter... it showed that 24 of 26 respondents work for companies that do not support contributing under an Unlicense/public domain model. I think my concern stands.

I wasn't trying to reject or dismiss your concern, and I appreciate that you have worked to substantiate it. I suggest that we use a public domain license (paired with a permissive one for jurisdictions where that's necessary) while that concern is hypothetical, and re-evaluate based on the actual situation once it arises. This leaves the project in a position to accommodate a major corporate contributor for whom the public domain is a dealbreaker, but is maximally permissive until that time arises.

Seems like we have a kind of decision tree here:

1. if we have to match the license of harfbuzz, the simplest thing is to license everything under that. Since it would then be impossible to place it into the public domain, no dual licensing makes sense.
1. if we do not have to match the old harfbuzz license, then we have advocates for:
    - Dual licensing between the public domain and a permissive license like the BSD
    - Solely licensing under a permissive license like the BSD

I guess we need an answer to the relicensing question first, and then the steering council can vote on the second if it's necessary.

**Comment by eliasnaur** [comment]
> > Rights not mentioned in a license are retained by the copyright holder. If the Old MIT license doesn't mention relicensing, we can't. It wouldn't make sense anyway: if we could relicense, what's different from the public domain?
> 
> Well, the question is really about whether or not a source port that no longer contains code from the original project is by default under the same license. @benoitkugler wrote the code, though using harfbuzz as a reference. Unlike the GPL, which virally requires that derived works in this fashion retain the same license, I don't see anything indicating that the Old MIT would work that way. Does anyone know a FOSS lawyer or licensing expert who could offer more informed thoughts?
> 

I don't think the license (GPL vs MIT vs Old MIT) matters here. If Benoit's work is a derivation of the original, his work can only be distributed according to the original license, whether that license is GPL, MIT or something else.

However, if Benoit was merely inspired by Harfbuzz, but otherwise wrote his work from the ground up, his work may not be considered derivative and he can license his work freely. It's my understanding that the work was a source level port, in which case I'm sure the original license apply to his work.

In other words, the amount of original code left in a work doesn't matter, what matters is the origin of the code.

However, IANAL, and would love to be proven wrong since Benoit can then license his work freely.

Note that the Harfbuzz license is not entirely clear. From their [COPYING](https://github.com/harfbuzz/harfbuzz/blob/main/COPYING):

> For parts of HarfBuzz that are licensed under different licenses see individual
files names COPYING in subdirectories where applicable.

> if we have to match the license of harfbuzz, the simplest thing is to license everything under that. Since it would then be impossible to place it into the public domain, no dual licensing makes sense.


This option depends on whether Benoit's port end up in a separate repository (but still under go-text). If so, I still think BSD+Unlicense is best for this repository (shaping), and the Harfbuzz license for the separate repository.

**Comment by benoitkugler** [comment]
> However, if Benoit was merely inspired by Harfbuzz, but otherwise wrote his work from the ground up, his work may not be considered derivative and he can license his work freely. It's my understanding that the work was a source level port, in which case I'm sure the original license apply to his work.

I can confirm that it is a source level port, essentially a translation from C++ to Go, with some adjustments (on font loading for instance). I won't pretend the core logic is an original work... 

How annoying would it be to use the same license as Harfbuzz ? I think it is compatible with the current license used by Fyne and Gio (in the sense that the toolkit could consume go-text without having to change their license), right?

**Comment by andydotxyz** [comment]
> It may simply be the case that the companies in question have never needed to contribute to a public domain project.

That may be true, but it was some data points. I was trying to provide more than personal opinion to explore whether I was alone in my concerns. However you read the numbers I think it indicates that I was not just worried about hypotheticals.

> I can't see why businesses should not also be asked to weigh practicality against convictions.

They probably can, but we are trying to make a decision and it seemed like some historical data might have helped to avoid the comments about my concerns being purely hypothetical. It is important to understand that businesses have approved open source licenses. Adding public domain/Unlicense to their lists is likely non-trivial.

> I can confirm that it is a source level port, essentially a translation from C++ to Go, with some adjustments (on font loading for instance). I won't pretend the core logic is an original work...

Thank you for this clarification. I am fairly sure this means it would be classified as a "derived work". Although MIT does not place restrictions on tracking changes or noting the source of the derived work I am pretty sure you cannot simply fork and Unlicense such a work. (disclaimer: I tried to find documentation on this specific path and couldn't)

> How annoying would it be to use the same license as Harfbuzz ? I think it is compatible with the current license used by Fyne and Gio (in the sense that the toolkit could consume go-text without having to change their license), right?

You are right it is compatible with Gio and Fyne, it would not pose any restrictions on those projects so I also don't see why it would be a problem.

**Comment by andydotxyz** [comment]
> Please share proposals for a licensing choice here. Some things to consider:

There have been some strong opinions expressed in the discussions above and I am not sure that all show the reasoning behind them. After reading this all I think that a point has been omitted thus far.

* On the video calls before this issue was opened the Gio contributors expressed a potential desire to extract `go-text` project code back into the `gio-core` repository in the future.

When you consider this additional point it becomes more clear why it is important for some to keep this project under Unlicense. I hold back from expressing my opinion on this reasoning, but I will suggest that if the copyright holders wish to move their contributions in the future they can do so without Unlicense applied to the collaborative work (as using a permissive license they will not have waived their copyright ownership of the original work).

**Comment by whereswaldon** [comment]
I've spent a lot of time thinking about this in the last week.

It's true that the harfbuzz port must be OLD-MIT licensed, so let's set that part aside for the moment.

I believe that it is in the best interests of users to have the option to consume this code under the public domain. I also have a strong preference that this code (the result of _months_ of my work) be in the public domain.

The licensing I have advocated above -- the Dual BSD/(Unlicense|CC0) -- respects what I think is right for users without preventing later reconsideration in light of the needs of a business.

I understand that some people here feel differently about the public domain and have different priorities, and that when collaborating you don't always get your way. That's fine. However, the reason to compromise for the sake of collaboration is in the hope that you will gain from the collaboration of the parties with whom you compromise. PR #5 met my needs from the moment I posted it, but since then I've spent a staggering amount of effort trying to make it suit the needs of @fyne-io. The revisions that were requested to that API each cost me lots of time and energy, and I do not value the resulting cleaner API over the time, energy, and frustration that it took to create.

I'm not certain that collaborating in this way makes sense if this is going to be the dynamic. I think that I differ not only on licensing preference, but in my fundamental approach to designing and building software. I prefer to allow abstractions to emerge from the domain, rather than trying to design abstractions/APIs up-front and make the domain fit them. This tension in design philosophies has (I think) driven a lot of the back&forth discussion, and I'm sure has been exhausting for everyone involved (it definitely has been for me). We might all be better served if I continue my efforts elsewhere in a public domain project that you can all consume and contribute to, but without pitting our development strategies against one another.

I think we all came into this with the best of intentions under the assumption that we should be able to figure something out here, but it seems that everything from our licensing strategies to our engineering values are in conflict. I'm open to continuing this collaboration, but only if we can resolve that somehow (and I don't see a good way forward right now).

**Comment by andydotxyz** [comment]
Thanks for sharing your thoughts on this @whereswaldon, I agree with many of the things you expressed, but I am not sure that things are as dire as you suggest...

With regards to collaboration I thought we were just getting to a good place. I was expecting that with #5 landed many more things could be done with more collaborators (I assumed that one doesn't change code on someone else's PR). If it was not for the license being included in the PR it seems like all the reviewers would be happy to see it land.

Is there a reason the two items (#5 and #6) cannot be separated?

As far as the license discussion goes I think that it is clear what each person's preferences are. Perhaps the only thing left to do is to hold a vote with the "deciding team" that was just set up?

I am looking forward to contributing, as I am sure others are too - but until we land #5 (and decide this license discussion) it seems unclear what we can do.

**Comment by whereswaldon** [comment]
> Is there a reason the two items (#5 and #6) cannot be separated?

Not a technical reason, but the resulting code is useless without a License attached. Also it seems pointless to remove them, since I do explicitly license the code that way, and it doesn't actually prevent anyone from changing the license later when they contribute (since it's public domain to start with).

> Perhaps the only thing left to do is to hold a vote with the "deciding team" that was just set up?

I fear that this isn't really fair to @benoitkugler. You (@andydotxyz) and I have both expressed our opinions, which forces @benoitkugler to act as the tiebreaker in a decision that he doesn't have a strong opinion about.

**Comment by andydotxyz** [comment]
> Also it seems pointless to remove them, since I do explicitly license the code that way

It is highly unusual for developers to contribute using their license choice rather than that of a project, which is why I think we must separate the two discussions.

> I fear that this isn't really fair to @benoitkugler. You (@andydotxyz) and I have both expressed our opinions, which forces @benoitkugler to act as the tiebreaker in a decision that he doesn't have a strong opinion about.

I am a little unsure how to proceed then. In the go-team channel the process we should use was agreed (the decision team) and the team was created. But now you don't want to follow the process that was set up.
What alternatives exist?

**Comment by benoitkugler** [comment]
I have thought a bit more about this issue and the two points I've understood are : 

- Going from Public domain to a more restrictive license is possible, and not the other way around
- As of yet, the main effort to implement the go-text shaper was provided by @whereswaldon (with valuable inputs from others, of course).

Thus, I think the dual license proposed by @whereswaldon is the more natural choice. It has my support in a formal vote.

**Comment by whereswaldon** [comment]
> I am a little unsure how to proceed then. In the go-team channel the process we should use was agreed (the decision team) and the team was created. But now you don't want to follow the process that was set up.

I guess this is moot. I didn't want to force @benoitkugler into an awkward position, but if he's okay with being the tiebreaker then it's fine.

I support the dual BSD/PublicDomain licensing as my formal vote as well. I'm open to using whichever of the CC0 or Unlicense is preferred, though I would default to recommending the Unlicense if nobody cares which is used.

**Comment by andydotxyz** [comment]
Sounds like we have a decision then 😄 .

As for which public domain license to use I have no opinion as I don't know the differences.

**Comment by whereswaldon** [comment]
I think that we can close this now that we've finished the vote.

**Comment by andydotxyz** [comment]
> I think that we can close this now that we've finished the vote.

Agreed.
I suppose I didn't include my "official" vote, which would be for a permissive license only, as discussed above.
The line above is just for the record - let's move forward and hopefully it all works out.
